### PR TITLE
Add figure showing level evolution for individual vendors

### PR DESCRIPTION
**Pull request by valosekj**
This PR adds function for generation of figures (one figure for each qMRI metric (FA, MD, MTsat, ...)) capturing level evolution for individual labels/ROIs (SC, WM, GM,...) per individual vendors (Siemens, GE, Philips).

Example output for FA (computed from a few subjects):

dti_fa_per_vendor

UPDATE - in the last commit https://github.com/sct-pipeline/normative-metrics/pull/5/commits/d1943505d794b0f4c4bef0a33ca464075c5911a0 I added besides mean also standard deviation (std is computed from sites mean values; in my testing dataset I have only one site for Philips, therefore its std=0):

dti_fa_per_vendor

### CODE REVIEW

**Comment by valosekj** [comment]
Hm, now I am thinking, what is better (more correct) for visualization of site variably for individual vendors - standard deviation or coefficient of variation? STD is proportional to the mean, COV normalizes STD to the mean. So, for the comparison of larger differences in mean, COV should be better.

**Review by jcohenadad — APPROVED** [review]
nice! i would keep mean and std here (not cov)

**Comment by jcohenadad** [comment]
@valosekj why not modifying the original generat-figure from the spine-generic repos? that would prevent having to maintain 2 similar functions instead of 1.

**Comment by valosekj** [comment]
> @valosekj why not modifying the original generat-figure from the spine-generic repos? that would prevent having to maintain 2 similar functions instead of 1.

Original `generate-figures` script creates figures from metrics extracted from whole C2-C5 area from whole SC ROI. Compared to that, this script works with metrics from individual C2, C3, C4 and C5 levels and various ROIs. This script at the same time not only generate figures, but also aggregates statistic across sites and vendors and save them as cvs files. (I should probably rename this script to something like `generate_figures_and_tables` or divide the script into one generating figures and second one aggregating statistics and creating csv tables).

The process of fetching of input csv files with metrics is also little bit different between this script and original `generate-figures` (one line for one subject in case of mean value from C2-5 area for SC vs multiple lines for one subject for individual cervical levels and multiple ROIs).

But of course, it should be possible. I am writing individual functionalities in this script as individual functions, so merge of both script should be possible relatively easily (I hope).

**Comment by jcohenadad** [comment]
I see. I guess the script `extract_normative_metrics.sh` could probably be integrated inside the spine-generic pipeline, but on the other hand it doesn't hurt too much to have a separate/more extensive pipeline in addition to spine generic. It's just that the core purpose of spine-generic is precisely to provide such statistics, so i thought it would make sense to generate that as part of the project.

**Comment by jcohenadad** [comment]
> I see. I guess the script `extract_normative_metrics.sh` could probably be integrated inside the spine-generic pipeline, but on the other hand it doesn't hurt too much to have a separate/more extensive pipeline in addition to spine generic. It's just that the core purpose of spine-generic is precisely to provide such statistics, so i thought it would make sense to generate that as part of the project.

to follow-up on that. A strong argument in favor of maintaining a single file (i am repeating myself 😉 ), is that the original file is not free from bugs. I've just found a problematic one (https://github.com/spine-generic/spine-generic/issues/178). So, as bugs are being fixed on the original file, they _also_ need to be fixed in this repos, which is prone to error and requires maintenance time.

**Comment by valosekj** [comment]
> 
> to follow-up on that. A strong argument in favor of maintaining a single file (i am repeating myself 😉 ), is that the original file is not free from bugs. I've just found a problematic one ([spine-generic/spine-generic#178](https://github.com/spine-generic/spine-generic/issues/178)). So, as bugs are being fixed on the original file, they _also_ need to be fixed in this repos, which is prone to error and requires maintenance time.

You are absolutely right! Maintaining of one script is much more easier than take care of more scripts for similar purposes. On the other hand, bug which you found in `compute_statistics` function https://github.com/spine-generic/spine-generic/issues/178#issue-686574484 should not be presented in `normative_metrics/generate_figures` because this function is not included inside this script.

But, for future bugs and maintenance, it is undoubtedly easier to have one script, I will start migration of  `normative_metrics/generate_figures` into `spine-generic/generate_figures`.

**Pull request merged**
